piVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-svc
  labels:
    app: kubernetes-demo
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: kubernetes-demo
---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: kubernetes-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
      - name: kubernetes-demo
        image: kubernetes-demo:v1
        ports:
        - containerPort: 8080
